### ISSUE TITLE
校园网时断时续

### ISSUE THREAD

**Issue by nevercodecorrect** [ShenHongFei/ssdut-free-ipv6-network-guide#1]
讲道理的话你用的是哪家vps啊，我在校园网上玩这玩意时断时续，很爆炸，一会就自动断掉了

**Comment by ShenHongFei** [comment]
bandwagonhost，当时选这个是能用支付宝。现在vultr好像也能用支付宝了。你可以试试。
断掉一个是因为不正确的Router Advertisement把默认网关挤掉了，还有可能是DHCP莫名其妙的过期，需要重新renew一下。
不过现在寝室校园网已经获取不到全球单播IPv6地址（以2001:开头的那个）了，可能是因为维修或者被相关部门禁用了，过一段时间再看看吧。
