### ISSUE TITLE
Get-NetRoute :  CIM 服务器上的 ROOT/StandardCimv2/MSFT_NetRoute 类实例的 CIM 查询有问题

### ISSUE THREAD

**Issue by TingAlex** [ShenHongFei/ssdut-free-ipv6-network-guide#2]
**PS C:\WINDOWS\system32> Get-NetRoute -AddressFamily IPv6 -InterfaceAlias 以太网 -DestinationPrefix "::/0"**
Get-NetRoute :  CIM 服务器上的 ROOT/StandardCimv2/MSFT_NetRoute 类实例的 CIM 查询: SELECT * FROM MSFT_NetRoute  WHERE ((DestinationPrefix LIKE '::/0')) AND ((InterfaceAlias LIKE '以太
网')) AND ((AddressFamily = 23)) 找不到任何匹配的 MSFT_NetRoute 对象。请验证查询参数，然后重试。
At line:1 char:1
+ Get-NetRoute -AddressFamily IPv6 -InterfaceAlias 以太网 -DestinationPref ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_NetRoute:String) [Get-NetRoute], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound,Get-NetRoute

**Comment by ShenHongFei** [comment]
现在寝室校园网已经获取不到全球单播IPv6地址（以2001:开头的那个）了，可能是因为维修或者被相关部门禁用了，过一段时间再看看吧。
