### ISSUE TITLE
服务器出问题了吗，已经ping不通了

### ISSUE THREAD

**Issue by fisherxt** [ShenHongFei/ssdut-free-ipv6-network-guide#4]
正在 Ping 2607:8700:101:3118:: 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

2607:8700:101:3118:: 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by ShenHongFei** [comment]
嗯，原来那个服务器过期了。
